name: Auto Format and Fix

on:
  push:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  lint-fix:
    if: github.repository == 'YuriSilenok/lern_tg_bot'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install black ruff

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Format code with black
      run: black .

    - name: Commit and push changes by black
      run: |
        if [[ $(git status --porcelain) ]]; then
          git add .
          git commit -m "chore: auto-fix formatting via GitHub Actions by black"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    - name: Format code with ruff
      run: ruff check . --fix --unsafe-fixes || true

    - name: Commit and push changes by ruff
      run: |
        if [[ $(git status --porcelain) ]]; then
          git add .
          git commit -m "chore: auto-fix formatting via GitHub Actions by ruff"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi
