name: Pipeline

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint-fix:
    uses: ./.github/workflows/lint-fix.yml

  lint-check:
    needs: lint-fix
    uses: ./.github/workflows/lint-check.yml
